exports.PostRouter = require('./posts.js')
// exports.CommentsRouter = require('./comment.js')
// exports.ProfileRouter = require('./profile.js')
exports.UserRouter = require('./users.js')
exports.SecurityRouter = require('./security.js')