exports.CommentsRouter = require('./comments.js')
exports.PostRouter = require('./posts.js')
exports.ProfileRouter = require('./profile.js')
exports.UserRouter = require('./users.js')
exports.SecurityRouter = require('./security.js') 
exports.FeedRouter = require ('./feed.js')
